# Generated by Django 5.0.7 on 2024-07-29 13:14

import lunarapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to=lunarapp.models.image_file_dir)),
                ('duration', models.IntegerField()),
                ('category', models.CharField(help_text=' Category of the course (e.g., Programming, Design)', max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the course is currently active')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('experience', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True)),
                ('duration', models.IntegerField()),
                ('type', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time')], max_length=50)),
                ('image', models.ImageField(upload_to=lunarapp.models.image_file_dir)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to=lunarapp.models.image_file_dir)),
                ('category', models.CharField(help_text='Category of the product(for e.g web, app)', max_length=100)),
                ('available', models.BooleanField(default=True, help_text='Whether the product is available for purchase')),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
