# Generated by Django 5.0.7 on 2024-07-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunarapp', '0002_rename_courses_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trending',
            field=models.BooleanField(default=False, help_text='0= default, 1= trending'),
        ),
        migrations.AddField(
            model_name='internship',
            name='trending',
            field=models.BooleanField(default=False, help_text='0= default, 1= trending'),
        ),
        migrations.AddField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False, help_text='0= default, 1= trending'),
        ),
    ]
