# Generated by Django 5.0.7 on 2024-08-10 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunarapp', '0004_all_user_alter_course_name_alter_internship_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunarapp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunarapp.all_user')),
            ],
        ),
    ]
