# Generated by Django 5.0.7 on 2024-08-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunarapp', '0005_coursepayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePayment',
        ),
    ]
