# Generated by Django 5.0.7 on 2024-08-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunarapp', '0008_course_is_intern_course_is_staff_course_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_Intern',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_Staff',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_Student',
        ),
        migrations.AddField(
            model_name='all_user',
            name='is_Intern',
            field=models.BooleanField(default=False, help_text='If the user is intern or not'),
        ),
        migrations.AddField(
            model_name='all_user',
            name='is_Staff',
            field=models.BooleanField(default=False, help_text='If the user is staff or not'),
        ),
        migrations.AddField(
            model_name='all_user',
            name='is_Student',
            field=models.BooleanField(default=False, help_text='If the user is student or not'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_purchased',
            field=models.BooleanField(default=False, help_text='If the user has made the payment of the course'),
        ),
        migrations.DeleteModel(
            name='CoursePayment',
        ),
    ]
