# Generated by Django 5.0.7 on 2024-08-12 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunarapp', '0009_remove_course_is_intern_remove_course_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'CREDIT_CARD'), ('PAYPAL', 'PAYPAL'), ('ESEWA', 'ESEWA'), ('KHALTI', 'KHALTI')], max_length=20)),
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=200, unique=True)),
                ('pidx', models.CharField(max_length=255, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunarapp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunarapp.all_user')),
            ],
        ),
    ]
